#pragma config(Motor,  motor4,          leftMotor,     tmotorVexIQ, PIDControl, reversed, encoder)
#pragma config(Motor,  motor5,          leftkouqiuMotor, tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor6,          leftarmMotor,  tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor10,         rightMotor,    tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor11,         rightkouqiuMotor, tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor12,         rightarmMotor, tmotorVexIQ, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
		int threshold = 20;
		int ls = 0;int rs = 0;

		while(true)
	  {
	  	 ls = 1.27*getJoystickValue(ChA)+ getJoystickValue(ChC)*1.27;
	  	 rs = 1.27*getJoystickValue(ChA-ChC)*1.27;

	  	 if (ls > threshold||ls <-threshold)
	  	 {
	  	   		setMotorSpeed(leftMotor,ls);
	     }
	     else
	     {
	          setMotorSpeed(leftMotor,0);
	     }
	     if (rs>threshold||rs<-threshold)
	     {
	          setMotorSpeed(rightMotor,rs);
	     }
	     else
	     {
	          setMotorSpeed(rightMotor,0);
	     }
	 }


}
